replicaCount: 1

image:
  repository: ccokee/slck
  pullPolicy: IfNotPresent
  tag: k9s

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 10443

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  service:
    type: NodePort
    port: 6379