version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOMAIN: localhost
        EMAIL: jcurr@unileon.es
        SLCK_REDIS_HOST: redis
        SLCK_REDIS_PORT: 6379
    image: your_project_image
    ports:
      - "10443:10443"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
