apiVersion: v1
kind: Service
metadata:
  name: {{ include "slck-chart.fullname" . }}-redis
  labels:
    {{- include "slck-chart.labels" . | nindent 4 }}
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: 6379
  type: ClusterIP
